name: Code Health (Build, Lint, & Test)
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}
          # registry-url: 'https://npm.pkg.github.com/'
          # scope: '@rms'
      - name: Install yarn
        run: npm install -g yarn
      - name: yarn install, build, lint, & test
        run: |
          yarn
          yarn build
          yarn lint
          yarn test
